# This workflow is created for the purpose of testing and experimenting with GitHub Actions.
# It is not intended for any real use within the project. 

name: Test Project
on: push
jobs:
  test:
    runs-on: ubunu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
    
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
    
